pipeline {
    agent any

    environment {
        DOCKER_PASSWORD = credentials('docker_password')
    }

    stages {
        stage('Build & Test') {
            steps {
                sh './gradlew clean build'
            }
        }

        stage('Prepare & Tag Image') {
            steps {
                script {
                    script {
                        GIT_TAG = sh([script: 'git fetch --tag && git tag', returnStdout: true]).trim()
                        MAJOR_VERSION = sh([script: 'git tag | cut -d . -f 1', returnStdout: true]).trim()
                        MINOR_VERSION = sh([script: 'git tag | cut -d . -f 2', returnStdout: true]).trim()
                        PATCH_VERSION = sh([script: 'git tag | cut -d . -f 3', returnStdout: true]).trim()
                    }
                    def NEW_TAG = "${MAJOR_VERSION}.\$((${MINOR_VERSION} + 1)).${PATCH_VERSION}"
                    sh "docker build -t tgeorget/hello-img:${NEW_TAG} ."

                    withCredentials([usernamePassword(credentialsId: 'docker_password', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        sh """
                            echo $PASSWORD | docker login docker.io -u $USERNAME --password-stdin
                            docker push tgeorget/hello-img:${NEW_TAG}
                        """
                    }

                }
            }
        }
    }
}